name: Sync mirror

on: 
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://github.com/samdev-7/ragno-site.git'
            GIT_USERNAME: "samdev-7"
            GIT_PASSWORD: ${{ secrets.PAT }}
            DEBUG: "true"
