name: Sync mirror

on: 
  push:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@v0.7.0
          with:
            REMOTE: 'https://gitlab.com/samdev-7/ragno-site.git'
            GIT_USERNAME: spyoungtech
            GIT_PASSWORD: ${{ secrets.MIRROR_PAT }}
